Backend: Vitis
ClockPeriod: 5
HLSConfig:
  LayerName:
    fc3:
      Precision:
        bias: fixed<8,5>
        result: fixed<16,6>
        weight: fixed<8,5>
      Trace: false
    fc3_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    flatten_22:
      Precision:
        result: fixed<16,6>
      Trace: false
    flatten_22_input:
      Precision:
        result: fixed<16,6>
      Trace: false
    output:
      Precision:
        bias: fixed<8,5>
        result: fixed<16,6>
        weight: fixed<8,5>
      Trace: false
    output_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    relu3:
      Precision:
        result: fixed<8,5,RND_CONV,SAT>
      Trace: false
    softmax:
      Precision:
        result: fixed<16,6>
      Strategy: Stable
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: ap_fixed<8,4>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
KerasModel: !keras_model 'hlsPrj//keras_model.h5'
OutputDir: hlsPrj/
Part: xc7z020clg484-1
ProjectName: myproject
Stamp: EbAA4aD6
Version: 1.0.0
